# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Cre8tive Wedding and Events
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  With over 25 years of experience, Cre8tiveLA will take your party to the next level whether it's a Wedding, Quinceañera, Corporate Event, or Private Party!
about: >- # this means to ignore newlines until "baseurl:"
  This will be the about text
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

welcome:
  section: welcome
  list:
    - title: "DJ/MC Service"
      desc: "With over 25 years of experience, Cre8tiveLA will take your party to the next level whether it's a Wedding, Quinceañera, Corporate Event, or Private Party!"
      img-link: "/assets/img/home/djmc-service.jpg"
    - title: "Event Planning"
      desc: "Event planning at its finest. Let Cre8tiveLA book all your vendors, coordinate the timeline, and run your event!"
      img-link: "/assets/img/home/event-planning.jpg"
    - title: "Custom Lighting"
      desc: "Transform your ordinary banquet hall into the space of your dreams with custom lighting options to create a cool vibe."
      img-link: "/assets/img/home/lighting.jpg"

vendors:
  section: vendors
  list:
    - title: "Lux Hair Studio"
      logo-link: "/assets/img/vendors/lux/lux-logo.webp"
      img1-link: "/assets/img/vendors/lux/1.png"
      img2-link: "/assets/img/vendors/lux/2.png"
      img3-link: "/assets/img/vendors/lux/3.png"
      img4-link: "/assets/img/vendors/lux/4.png"
      img5-link: "/assets/img/vendors/lux/5.jpg"
      img6-link: "/assets/img/vendors/lux/6.jpg"
      carousel-id: "carouselLux"
      modal-id: "modalLux"
      ig-link: "https://www.instagram.com/luxxhair/"
      yelp-link: "https://www.yelp.com/biz/lux-hair-studio-torrance"
      services: "Hair Stylist/Makeup Artist"
      name: "Nancy Toro"
    - title: "Exclusive Party Rentals"
      logo-link: "/assets/img/vendors/exclusive-party-rentals/exclusive-party-rentals-logo.png"
      img1-link: "/assets/img/vendors/exclusive-party-rentals/exclusive-party-rentals1.png"
      img2-link: "/assets/img/vendors/exclusive-party-rentals/exclusive-party-rentals2.png"
      img3-link: "/assets/img/vendors/exclusive-party-rentals/exclusive-party-rentals3.png"
      img4-link: "/assets/img/vendors/exclusive-party-rentals/exclusive-party-rentals4.png"
      img5-link: "/assets/img/vendors/exclusive-party-rentals/exclusive-party-rentals5.png"
      img6-link: "/assets/img/vendors/exclusive-party-rentals/exclusive-party-rentals6.png"
      carousel-id: "carouselExclusives"
      modal-id: "modalExclusives"
      gal-link: "/portfolio/space-wcrb/#exclusive-party-rentals"
      services: "Party Rentals"
      name: "Yasmin"
    - title: "Analexa's Events"
      logo-link: "/assets/img/vendors/analexas/analexas-events-logo.jpg"
      img1-link: "/assets/img/vendors/analexas/analexas-events1.png"
      img2-link: "/assets/img/vendors/analexas/analexas-events2.png"
      img3-link: "/assets/img/vendors/analexas/analexas-events3.png"
      img4-link: "/assets/img/vendors/analexas/analexas-events4.png"
      img5-link: "/assets/img/vendors/analexas/analexas-events5.png"
      img6-link: "/assets/img/vendors/analexas/analexas-events6.png"
      carousel-id: "carouselAnalexas"
      modal-id: "modalAnalexas"
      ig-link: "https://www.instagram.com/analexas/"
      yelp-link: "https://www.yelp.com/biz/analexas-events-san-pedro-2"
      gal-link: "/portfolio/space-wcrb/#analexas-events"
      services: "Event Planning/Decor"
      name: "Analexa"
    - title: "Raul's Bartending"
      logo-link: "/assets/img/vendors/rauls-bartending-service/rauls-bartending-service-logo.png"
      img1-link: "/assets/img/vendors/rauls-bartending-service/rauls-bartending-service1.png"
      img2-link: "/assets/img/vendors/rauls-bartending-service/rauls-bartending-service2.png"
      img3-link: "/assets/img/vendors/rauls-bartending-service/rauls-bartending-service3.png"
      img4-link: "/assets/img/vendors/rauls-bartending-service/rauls-bartending-service4.png"
      img5-link: "/assets/img/vendors/rauls-bartending-service/rauls-bartending-service5.png"
      img6-link: "/assets/img/vendors/rauls-bartending-service/rauls-bartending-service6.png"
      carousel-id: "carouselRauls"
      modal-id: "modalRauls"
      gal-link: "/portfolio/space-wcrb/#rauls-bartending-service"
      services: "Bartending"
      name: "Raul"
    - title: "Miriam's Flowers"
      logo-link: "/assets/img/vendors/miriams-flowers/miriams-flowers-logo.png"
      img1-link: "/assets/img/vendors/miriams-flowers/miriams-flowers1.jpg"
      img2-link: "/assets/img/vendors/miriams-flowers/miriams-flowers2.jpg"
      img3-link: "/assets/img/vendors/miriams-flowers/miriams-flowers3.png"
      img4-link: "/assets/img/vendors/miriams-flowers/miriams-flowers4.png"
      img5-link: "/assets/img/vendors/miriams-flowers/miriams-flowers5.png"
      img6-link: "/assets/img/vendors/miriams-flowers/miriams-flowers6.png"
      carousel-id: "carouselMiriams"
      modal-id: "modalMiriams"
      gal-link: "/portfolio/space-wcrb/#miriams-flowers"
      services: "Florist"
      name: "Miriam"
    - title: "Photography by Ricardo"
      logo-link: "/assets/img/vendors/photo-ricardob/photography-by-ricardo-logo.webp"
      img1-link: "/assets/img/vendors/photo-ricardob/photography-by-ricardo1.png"
      img2-link: "/assets/img/vendors/photo-ricardob/photography-by-ricardo2.png"
      img3-link: "/assets/img/vendors/photo-ricardob/photography-by-ricardo3.png"
      img4-link: "/assets/img/vendors/photo-ricardob/photography-by-ricardo4.png"
      img5-link: "/assets/img/vendors/photo-ricardob/photography-by-ricardo5.png"
      img6-link: "/assets/img/vendors/photo-ricardob/photography-by-ricardo6.png"
      carousel-id: "carouselRicardoB"
      modal-id: "modalRicardoB"
      ig-link: "https://www.instagram.com/photographybyricardo/"
      gal-link: "/portfolio/space-wcrb/#photography-by-ricardo"
      services: "Photography/Videography"
      name: "Ricardo Barrera"
    - title: "Catering by Chef Martin"
      logo-link: "/assets/img/vendors/catering-by-chef-martin/catering-by-chef-martin-logo.png"
      img1-link: "/assets/img/vendors/catering-by-chef-martin/catering-by-chef-martin1.png"
      img2-link: "/assets/img/vendors/catering-by-chef-martin/catering-by-chef-martin2.png"
      img3-link: "/assets/img/vendors/catering-by-chef-martin/catering-by-chef-martin3.png"
      img4-link: "/assets/img/vendors/catering-by-chef-martin/catering-by-chef-martin4.png"
      img5-link: "/assets/img/vendors/catering-by-chef-martin/catering-by-chef-martin5.png"
      img6-link: "/assets/img/vendors/catering-by-chef-martin/catering-by-chef-martin6.png"
      carousel-id: "carouselMartins"
      modal-id: "modalMartins"
      gal-link: "/portfolio/space-wcrb/#catering-by-chef-martin"
      services: "Catering"
      name: "Martin"
    - title: "Lupita's Tacos"
      logo-link: "/assets/img/vendors/lupitas-tacos/lupitas-tacos-logo.png"
      img1-link: "/assets/img/vendors/lupitas-tacos/lupitas-tacos1.png"
      img2-link: "/assets/img/vendors/lupitas-tacos/lupitas-tacos2.png"
      img3-link: "/assets/img/vendors/lupitas-tacos/lupitas-tacos3.png"
      img4-link: "/assets/img/vendors/lupitas-tacos/lupitas-tacos4.png"
      img5-link: "/assets/img/vendors/lupitas-tacos/lupitas-tacos5.png"
      img6-link: "/assets/img/vendors/lupitas-tacos/lupitas-tacos6.png"
      carousel-id: "carouselLupitas"
      modal-id: "modalLupitas"
      gal-link: "/portfolio/space-wcrb/#lupitas-tacos"
      services: "Tacos"
      name: "Pablo y Alma"

services:
  section: services
  list:
    - title: "Wedding Planning"
      desc: "We offer a range of wedding planning services, including Day of Wedding Planning and Complete Wedding Planning options. Our services cover everything from booking all wedding vendors to arranging transportation to vendor meetings, while benefiting from unlimited office consultations. We handle vendor payments, on your behalf, with the convenience of a single invoice. Our fee structure involves a 20% charge based on the entire invoice. Our professional staff ensures seamless event execution."
      icon-link: "fa-solid fa-ring fa-stack-1x fa-inverse"
    - title: "Event Planning"
      desc: "Our services cover a wide spectrum of events, including Corporate Events, Quinceañeras, and Ceremonies. We also provide a variety of additional offerings such as PA Systems, Photobooths, Photographers, Videographers, Catering, and Decor. Furthermore, we offer Video Projectors and Screens, Florists, Venues, Hair Stylists, Makeup Artists, Casino Party Rentals, as well as accessories like Step and Repeat Banners, Red Carpet, and Velvet Rope Stanchions."
      icon-link: "fa-solid fa-cake-candles fa-stack-1x fa-inverse"

packages:
  section: packages
  list:
    - title: "Silver Package"
      price: "$2000"
      color: "bg-secondary-subtle"
    - title: "Gold Package"
      price: "$2700"
      color: "bg-warning"
    - title: "Diamond Package"
      price: "$4300"
      color: "bg-light"

contact:
  section: contact
  list:
    - title: "Event Planning"
    - title: "Corporate Event"
    - title: "DJ/MC Service"
    - title: "Custom Lighting"
    - title: "Ceremony Service"
    - title: "Venue"
    - title: "Photographer"
  list2:
    - title: "Caterer"
    - title: "Hair Stylist"
    - title: "Florist"
    - title: "Decor"
    - title: "Photobooth"
    - title: "Dance Choreography"
    - title: "Red Carpet Entrance/Media Wall"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
